### ISSUE TITLE
The new exp method in Misc/Series.jl is not used and does not pass the tests

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#750] opened 2021-02-13 12:39 UTC
First of all, the method is not used because it does not extend `Base.exp`

Even even if we change it to extend `Base.exp`, the tests would fail because of the following (`exp` is calling https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/RelSeries.jl#L1036 and `Generic.exp` is calling https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/Misc/Series.jl#L47):

```julia
julia> using AbstractAlgebra

julia> Qx, x = PowerSeriesRing(QQ, 10, "x");

julia> exp(x + O(x^1)) == exp(x + O(x^2))
true

julia> Generic.exp(x + O(x^1)) == Generic.exp(x + O(x^2))
false

julia> exp(x + O(x^1))
1 + O(x^1)

julia> Generic.exp(x + O(x^1))
1 + O(x^2)

julia> exp(x + O(x^2))
1 + x + O(x^2)

julia> Generic.exp(x + O(x^2))
1 + x + O(x^2)
```
@wbhart @fieker

**Comment by fieker** [comment] 2021-02-15 09:23
There are problems with (here I'd say) the flint stuff:
Qx, x = PowerSeriesRing(QQ, 10, "x");
y = (2*x^5 + O(x^6))

Then
julia> y^0
1 + O(x^1)

and, I think doing exp "by hand":
1+y+y^2*fmpq(1,2)
gives
1 + 2*x^5 + O(x^6)
Base.

Further reading: log seems to be the culprit:
julia> log(1+O(x^3))
O(x^10)

using the power series: 
julia> y = 1+O(x^2)
1 + O(x^2)
julia> (y-1) - (y-1)^2*fmpq(1, 2) + (y-1)^3*fmpq(1, 3)
O(x^2)

while Nemo gives O(x^10) - the ring precision.

**Comment by fieker** [comment] 2021-02-15 09:29
Problem found - but the same probelm is elsewhere in Nemo:
function log(a::fmpq_rel_series)
   (a.val != 0 || coeff(a, 0) != 1) && error("Constant term not one in log")
   if pol_length(a) + valuation(a) == 1 || a.prec < 2
      return parent(a)()
   end
   z = parent(a)()

This "shortcut" returns the wrong precision, it should be
function log(a::fmpq_rel_series)
   (a.val != 0 || coeff(a, 0) != 1) && error("Constant term not one in log")
   z = parent(a)()
   z.prec = a.prec
   z.val = 0
   if pol_length(a) + valuation(a) == 1 || a.prec < 2
      return z
   end

The "same" is likely to be in tan, tanh, sin, sinh, cos, ...
in exp it is caught.

This now shows as the generic stuff from Hecke uses different, asymptotically faster methods, thus a completely different calling tree (exp as the inverse to log, hence exp is now "funny" as the old log function is called)

**Comment by fieker** [comment] 2021-02-15 10:30
I have a patch that makes Nemo tests pass, PR is coming

**Comment by fieker** [comment] 2021-02-15 10:31
Sorry - the closing was accidental

**Comment by thofma** [comment] 2021-02-15 10:31
Thanks. I will keep this open here, since there some things to sort.

**Comment by fieker** [comment] 2021-02-15 10:34
It does not fix the issues that exp log are now slower.... (for fmpq_rel_series)

**Comment by fieker** [comment] 2021-02-15 10:35
darn. I assume all series (14 files) have this problem

**Comment by fieker** [comment] 2021-02-15 16:07
actually: in flint, the fast methods are used. My guess is that the Hecke versions were added at a a time when they were not bound in Nemo.
They are still useful (and should be kept) for example number fields
Possibly supplemented by modular methods

**Comment by wbhart** [comment] 2021-02-19 03:38
Could we possibly open tickets for whatever remains.  I'm confused at this point as to what the current status is.

As far as I see from the original report, the code from Hecke was returning wrong answers and the existing code from AbstractAlgebra was being used anyway which is why this didn't show up.

Now that this has been fixed we overload Base.exp for series over rings in generic/RelSeries.jl and over fields in generic/Misc/RelSeries.jl.

Then there are comments about Flint, even though this is AbstractAlgebra and both of these implementations are generic. @fieker fixed some bugs in the Nemo series code. The relationship between the two things is unclear to me.

It may be worth mentioning that at this point all I have done is move the code over, clean things up very minimally and fixed stuff until the tests passed. There's a lot to do to integrate all this code properly.

**Comment by wbhart** [comment] 2021-02-19 03:40
By the way, the same issue exists for the inv implementation. We also don't import inv from Base which means the code in Misc/Series.jl is not actually being called.

This is something I would ostensibly attend to when integrating the code properly.

**Comment by wbhart** [comment] 2021-02-19 04:00
See #756 which enables inv. The AbstractAlgebra and Nemo tests continue to pass with that change.

**Comment by fieker** [comment] 2021-02-19 07:31
On Thu, Feb 18, 2021 at 07:38:25PM -0800, wbhart wrote:
> Could we possibly open tickets for whatever remains.  I'm confused at this point as to what the current status is.
Am I as confused.
> 
> As far as I see from the original report, the code from Hecke was returning wrong answers and the existing code from AbstractAlgebra was being used anyway which is why this didn't show up.
No, more complicated. The Hecke stuff was returning wrong results in
precision < 2 (the result was always >= 2)

The Nemo stuff was returning wrong results (full precision) on trivial
input.

The combination was deadly.
power_sum_to_poly is calling exp and was calling Hecke exp, possibly
because they were both in Generic?
The Hecke-exp ended up calling the Nemo-log, and this combination turned
out to be bad....
> 
> Now that this has been fixed we overload Base.exp for series over rings in generic/RelSeries.jl and over fields in generic/Misc/RelSeries.jl.
> 
> Then there are comments about Flint, even though this is AbstractAlgebra and both of these implementations are generic. @fieker fixed some bugs in the Nemo series code. The relationship between the two things is unclear to me.
> 
> It may be worth mentioning that at this point all I have done is move the code over, clean things up very minimally and fixed stuff until the tests passed. There's a lot to do to integrate all this code properly.

The problem is/was that this was exercising the wrong tests - or
depending on your view, there were not enough tests. The tests in Hecke
and Oscar triggered the problems immediately.

**Closed** 2021-02-25 14:27 UTC
