### ISSUE TITLE
docstrings should not be added for every method of a function

### ISSUE THREAD

**Issue by rfourquet** [Nemocas/AbstractAlgebra.jl#535] opened 2019-11-22 11:42 UTC
The other day I wanted to know what `divexact` means, so I went in help mode:
```julia
help> divexact(10, 3)
  divexact(a::AbstractAlgebra.ResElem{T}, b::AbstractAlgebra.ResElem{T}) where {T <: RingElement}

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.ResFieldElem{T}, b::AbstractAlgebra.ResFieldElem{T}) where {T <: RingElement}

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(f::AbstractAlgebra.PolyElem{T}, g::AbstractAlgebra.PolyElem{T}) where {T <: RingElement}

  │  Return f/g where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.PolyElem{T}, b::T) where {T <: RingElem}

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.PolyElem, b::Union{Integer, Rational, AbstractFloat})

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.RelSeriesElem{T}, y::AbstractAlgebra.RelSeriesElem{T}) where {T <: RingElement}

  │  Return x/y.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.RelSeriesElem, y::Union{Integer, Rational, AbstractFloat})

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.RelSeriesElem{T}, y::T) where {T <: RingElem}

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.AbsSeriesElem{T}, y::AbstractAlgebra.AbsSeriesElem{T}) where {T <: RingElement}

  │  Return x/y.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.AbsSeriesElem, y::Union{Integer, Rational, AbstractFloat})

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::AbstractAlgebra.AbsSeriesElem{T}, y::T) where {T <: RingElem}

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.LaurentSeriesElem{T}, y::Generic.LaurentSeriesElem{T}) where {T <: RingElement}

  │  Return x/y.

  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[25/8474]

  divexact(x::Generic.LaurentSeriesElem, y::Union{Integer, Rational, AbstractFloat})

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.LaurentSeriesElem{T}, y::T) where {T <: RingElem}

  │  Return x/y where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.PuiseuxSeriesElem, y::Union{Integer, Rational, AbstractFloat})

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.PuiseuxSeriesElem{T}, y::T) where {T <: RingElem}

  │  Return a/b where the quotient is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.MatrixElem, y::Union{Integer, Rational, AbstractFloat})

  │  Return x/y, i.e. the matrix where each of the entries has been divided by y. Each division is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(x::Generic.MatrixElem{T}, y::T) where {T <: RingElem}

  │  Return x/y, i.e. the matrix where each of the entries has been divided by y. Each division is expected to be exact.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.FracElem{T}, b::AbstractAlgebra.FracElem{T}) where {T <: RingElem}

  │  Return a/b.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.FracElem, b::Union{Integer, Rational, AbstractFloat})

  │  Return a/b.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::Union{Integer, Rational, AbstractFloat}, b::AbstractAlgebra.FracElem)

  │  Return a/b.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::AbstractAlgebra.FracElem{T}, b::T) where {T <: RingElem}

  │  Return a/b.

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  divexact(a::T, b::AbstractAlgebra.FracElem{T}) where {T <: RingElem}

  │  Return a/b.
```
RIght, about 23 similar docstrings. With `Nemo` loaded, there will be about 32. 
One problem is that as there is no specific docstring for `divexact(10, 3)`, the docstrings for all the methods are shown. Then I have to infer from unmatching docstrings what it would mean. At least, if there is a matching documented method, I get only one docstring instead of this wall of duplication. But if I ask for help on `divexact` (the function, not a method), I can't escape this tedious exercise of gazing at these specific docstrings to reconstruct the general meaning.
Another problem is that if there is a mistake in the docstring, it has to be fixed in all which contain the same mistake (usual problem with copy-pasting), cf. e.g.  https://github.com/Nemocas/Nemo.jl/pull/726.

Also, from Julia's [documentation](https://docs.julialang.org/en/v1.4-dev/manual/documentation/#Functions-and-Methods-1) on documentation:
> Functions in Julia may have multiple implementations, known as methods. While it's good practice for generic functions to have a single purpose, Julia allows methods to be documented individually if necessary. In general, only the most generic method should be documented, or even the function itself (i.e. the object created without any methods by `function bar end`). Specific methods should only be documented if their behaviour differs from the more generic ones. In any case, they should not repeat the information provided elsewhere. For example:

**Comment by fieker** [comment] 2019-11-22 11:54
On Fri, Nov 22, 2019 at 03:42:33AM -0800, Rafael Fourquet wrote:
> The other day I wanted to know what `divexact` means, so I went in help mode:
> ```julia
> help> divexact(10, 3)
>   divexact(a::AbstractAlgebra.ResElem{T}, b::AbstractAlgebra.ResElem{T}) where {T <: RingElement}
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.ResFieldElem{T}, b::AbstractAlgebra.ResFieldElem{T}) where {T <: RingElement}
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(f::AbstractAlgebra.PolyElem{T}, g::AbstractAlgebra.PolyElem{T}) where {T <: RingElement}
> 
>   │  Return f/g where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.PolyElem{T}, b::T) where {T <: RingElem}
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.PolyElem, b::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.RelSeriesElem{T}, y::AbstractAlgebra.RelSeriesElem{T}) where {T <: RingElement}
> 
>   │  Return x/y.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.RelSeriesElem, y::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.RelSeriesElem{T}, y::T) where {T <: RingElem}
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.AbsSeriesElem{T}, y::AbstractAlgebra.AbsSeriesElem{T}) where {T <: RingElement}
> 
>   │  Return x/y.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.AbsSeriesElem, y::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::AbstractAlgebra.AbsSeriesElem{T}, y::T) where {T <: RingElem}
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.LaurentSeriesElem{T}, y::Generic.LaurentSeriesElem{T}) where {T <: RingElement}
> 
>   │  Return x/y.
> 
>   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[25/8474]
> 
>   divexact(x::Generic.LaurentSeriesElem, y::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.LaurentSeriesElem{T}, y::T) where {T <: RingElem}
> 
>   │  Return x/y where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.PuiseuxSeriesElem, y::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.PuiseuxSeriesElem{T}, y::T) where {T <: RingElem}
> 
>   │  Return a/b where the quotient is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.MatrixElem, y::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return x/y, i.e. the matrix where each of the entries has been divided by y. Each division is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(x::Generic.MatrixElem{T}, y::T) where {T <: RingElem}
> 
>   │  Return x/y, i.e. the matrix where each of the entries has been divided by y. Each division is expected to be exact.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.FracElem{T}, b::AbstractAlgebra.FracElem{T}) where {T <: RingElem}
> 
>   │  Return a/b.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.FracElem, b::Union{Integer, Rational, AbstractFloat})
> 
>   │  Return a/b.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::Union{Integer, Rational, AbstractFloat}, b::AbstractAlgebra.FracElem)
> 
>   │  Return a/b.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::AbstractAlgebra.FracElem{T}, b::T) where {T <: RingElem}
> 
>   │  Return a/b.
> 
>   ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
>   divexact(a::T, b::AbstractAlgebra.FracElem{T}) where {T <: RingElem}
> 
>   │  Return a/b.
> ```
> RIght, about 23 similar docstrings. With `Nemo` loaded, there will be about 32. 
> One problem is that as there is no specific docstring for `divexact(10, 3)`, the docstrings for all the methods are shown. Then I have to infer from unmatching docstrings what it would mean. At least, if there is a matching documented method, I get only one docstring instead of this wall of duplication. But if I ask for help on `divexact` (the function, not a method), I can't escape this tedious exercise of gazing at these specific docstrings to reconstruct the general meaning.
> Another problem is that if there is a mistake in the docstring, it has to be fixed in all which contain the same mistake (usual problem with copy-pasting), cf. e.g.  https://github.com/Nemocas/Nemo.jl/pull/726.
> 
> Also, from Julia's [documentation](https://docs.julialang.org/en/v1.4-dev/manual/documentation/#Functions-and-Methods-1) on documentation:
> > Functions in Julia may have multiple implementations, known as
> > methods. While it's good practice for generic functions to have a
> > single purpose, Julia allows methods to be documented individually
> > if necessary. In general, only the most generic method should be
> > documented, or even the function itself (i.e. the object created
> > without any methods by `function bar end`). Specific methods should
> > only be documented if their behaviour differs from the more generic
> > ones. In any case, they should not repeat the information provided
> > elsewhere. For example:
> 
All agreed - but in general you will not be able to escape this: for
certain functions, even +, the behaviour is suffciently different to
warrant docstrings:
what is + for graphs, groups, ?
My personal favourite is order:
  can be an integer
  can be a ring
  can be an ordering
in particular, there is no most general one.

For divexact, as above, it could and probably should be done.
Probably with 2 strings
 - for fields, where it always succeeds (barring div by 0)
 - for rings, where it can fail (and throw an error)

**Comment by rfourquet** [comment] 2019-11-22 11:55
As far as I can tell, there could be only one docstring, like:
```julia
    divexact(x, y::RingElement)

Return `x/y`, where the division is expected to be exact. If it's not, an exception is thrown.
```

**Comment by rfourquet** [comment] 2019-11-22 11:59
> For divexact, as above, it could and probably should be done.
> Probably with 2 strings

I just suggested one docstring before seeing your message. Yes, one or two is fine. 23 is not. With my example above, it could be amended as:

```
Return `x/y`, where the division is expected to be exact (always true if `x` and `y` are field elements). If it's not, an exception is thrown.
```

**Comment by wbhart** [comment] 2019-11-22 12:04
We were previously unaware that you could add empty functions to Julia. So I agree that if we add such empty functions to Rings.jl in AbstractAlgebra, we could remove all the unnecessary docstrings which do not change the definition of the function.

For example, the function divexact should generally have the docstring:

"Return x/y where the division must be exact. If it is not an exact division, an exception is raised."

I realise that's not what is currently written, but it;'s also not the behaviour we originally started with for divexact. We ended up discovering that the generic interpolation code is invalid if an exception is not raised. We have also moved much more towards a system which tries to alert the user about what may be errors in their code, rather than to give a definition to things that might indicate a bug in their code, e.g. this came up in the discussion about one and identity_matrix vs diagonal_matrix in our recent Oscar meeting.

**Comment by rfourquet** [comment] 2019-11-22 12:13
> for certain functions, even +, the behaviour is suffciently different to warrant docstrings:

Yes of course. I'm just against repetition, e.g. seeing a bunch of `Return x + y` in docstrings for `+` dilutes the information.

> We were previously unaware that you could add empty functions to Julia.

Yes it's practical when you want to document the overall meaning. It's also possible to document a particular set of methods, like this:
```julia
"""
    divexact(x::FieldElem, y::FiedlElem)

Return x/y
"""
divexact(::FieldElem, ::FieldElem)
```
even though there is no _one_ specific method with this signature. It will apply to all methods whose signature is more specific than this one.

So as you both seem to agree, I will start fixing that here and there.

**Comment by wbhart** [comment] 2019-11-22 12:21
Yeah, I wouldn't add the bit about fields, otherwise we'll have to start adding all situations where it is always true. Let mathematicians figure that out.

We might, however, think about adding something about division by zero. If I am not mistaken, we always raise an exception if we try to divide by zero. E.g.  the current Oscar documentation for divexact contains the wording:

"Exact division raises an exception if the division is not exact, or if division by zero is attempted."

Of course you have to get up pretty early in the morning to check what has changed in Oscar on a daily basis. So don't quote me on this tomorrow or the next day.

**Comment by rfourquet** [comment] 2019-11-22 12:39
> Let mathematicians figure that out.

Agreed!

Another related issue is the required effort to maintain documentation in different places: the docstring, the `AbstractAlgebra` docs, e.g. for [`divexact`](https://nemocas.github.io/AbstractAlgebra.jl/latest/rings/#Exact-division-1) in the "required function for all rings" section:

```
divexact(f::MyElem, g::MyElem)
```
> Return f/gf/g, though note that Julia uses / for floating point division. Here we mean exact division in the ring, i.e. return qq such that f=gqf=gq. A DivideError() should be thrown if gg is zero. If no exact quotient exists or an impossible inverse is unavoidably encountered, an error should be thrown.

And then the documentation for Oscar. In each case the target audience might be slighly different, but it would be great if we can think of a way to reduce the amount of work. For example in the point 10. in Julia's [doc](https://docs.julialang.org/en/v1.4-dev/manual/documentation/#Documentation-1):

> Provide information allowing custom types to implement the function in an # Implementation section. These implementation details intended for developers rather than users, explaining e.g. which functions should be overridden and which functions automatically use appropriate fallbacks, are better kept separate from the main description of the function's behavior.

This could be applied to reuse the docstring of `divexact` in `AbstractAlgebra`'s docs.

**Comment by wbhart** [comment] 2019-11-22 12:40
How will you document in the online documentation, which types can be passed to a given function if you don't have docstrings for each. Generally there is more than one docstring because there is more than one section of the documentation that needs it.

For functions like divexact, which apply to all rings, it's not a problem. But this is a very small number of functions (they are described in the Ring interface in the AbstractAlgebra documentation). In general, in Nemo, functions are *only* documented if they provide functionality different from what is in the AbstractAlgebra documentation. In other words, we document that the given function is provided for that specific ring, even though it is not mandated for all rings.

It's not clear you are going to get far with this.

**Comment by rfourquet** [comment] 2019-11-22 12:46
I don't fully understand your last comment.

>  How will you document in the online documentation, which types can be passed to a given function if you don't have docstrings for each

By listing all the functions which are implemented for this particular type? It's possible to make the name of the function link to its documented place in the manual, so that the definition is just one click away.

**Comment by wbhart** [comment] 2019-11-22 12:46
@rfourquet We are not using docstrings in Oscar. It's a handwritten user manual, designed to explain things to users.

For one things, such a manual does not document all the functions that are available for all rings, then expect everyone to remember that in the section on Euclidean domains, or their specific ring that they are looking up. No one can read documentation like that, as our users have already amply proved.

I continually get emails suggesting they have only read the Nemo docs without reading the relevant AbstractAlgebra docs, even though virtually every single page in the Nemo docs links to the appropriate AbstractAlgebra documentation.

People just don't read documentation that way. We have to duplicate the information in the location they expect to find it. In such cases, the full docstring for the most generic case probably isn't all that useful. They will want a summary of the functions available by virtue of their particular ring of interest being a ring, followed by a more detailed treatment of their specific ring, intermixed with relevant examples and clear mathematical definitions.

I've thought about it, and there's just no way to do that properly with one-size-fits-all docstrings.

**Comment by wbhart** [comment] 2019-11-22 12:50
@rfourquet That will work in some cases. In other cases it's going to piss off users that they have to keep clicking all over the place to find the documentation they are looking for.

What you are trying to do is make it easy for the developer of the system, not for the user. That's just not going to work in general. You need to take a middle road, at the very least.

**Comment by wbhart** [comment] 2019-11-22 12:52
In any event, the exact types that are accepted aren't obvious. It's fine if it's a function of the form blah(a::T, b::T) on the page documenting type T. But for other mixed signatures and the like, it often depends on what is actually implemented. At present, we try to document the exact types that are accepted, and this is done by adding docstrings to the exact methods implemented.

**Comment by fieker** [comment] 2019-11-22 12:54
On Fri, Nov 22, 2019 at 04:46:55AM -0800, wbhart wrote:
> @rfourquet We are not using docstrings in Oscar. It's a handwritten user manual, designed to explain things to users.
@wbhart: Bill does not liek the docstrings (for the reason you
discovered), Oscar will have to have them.
> 
> For one things, such a manual does not document all the functions that
> are available for all rings, then expect everyone to remember that in
> the section on Euclidean domains, or their specific ring that they are
> looking up. No one can read documentation like that, as our users have
> already amply proved.
> 
> I continually get emails suggesting they have only read the Nemo docs
> without reading the relevant AbstractAlgebra docs, even though
> virtually every single page in the Nemo docs links to the appropriate
> AbstractAlgebra documentation.
> 
> People just don't read documentation that way. We have to duplicate
> the information in the location they expect to find it. In such cases,
> the full docstring for the most generic case probably isn't all that
> useful. They will want a summary of the functions available by virtue
> of their particular ring of interest being a ring, followed by a more
> detailed treatment of their specific ring, intermixed with relevant
> examples and clear mathematical definitions.

I beg to differ: the most important source of information for a
day-to-day user, apart from the source, are the docstrings.
In my experience, no-one will ever lookup gcd in the section on
euclidean rings. They will expect it to work.
gcdx I'd look up, just to make sure I understand in which order the
values are returned.
THE user-documentation I turn to as a last ditch effort.

> I've thought about it, and there's just no way to do that properly
> with one-size-fits-all docstrings.
It is also not possible to do this without.

**Comment by rfourquet** [comment] 2019-11-22 13:13
> In other cases it's going to piss off users that they have to keep clicking all over the place to find the documentation they are looking for.

My experience as a _user_ is also to be pissed off by being fed with the same copy-pasted information in different places, and I like terseness. I want to know were to look to get the reference on a particular function, which I wish was the docstring. The online documentation in my view should serve to provide information and insight into the system which doesn't fit docstrings. Another example is "examples": currently we have a bunch of them in the online documentation, but rarely in the docstrings, so I'm annoyed to have to go look online for examples after failing to get some in the docstring.

But I appreciate that you want to cater for the needs in the Oscar documentation that your write. Maybe it would be easier to discuss directly to see if we can find a more satisfying solution.

> At present, we try to document the exact types that are accepted, and this is done by adding docstrings to the exact methods implemented.

My take is that this should be changed. Docstring are not meant to document which method is implemented, and this leads to the example in the OP.

**Comment by wbhart** [comment] 2019-11-22 13:31
@fieker I am not disagreeing with you on any of these points. It's not that I don't think there should be docstrings, or that terseness in what is presented in the Julia REPL help is not desirable. It absolutely is!

I'm simply asking a question: "how are you going to handle documenting functions where a one-size-fits-all docstring does not apply". I gave examples.

At present, we pull in a good proportion of all the docstrings currently given, somewhere in the documentation.

If it would not embarrass actual living people who use our stuff, I would post here copies of the emails in which they were clearly reading our documentation, but obviously ignored the links to elsewhere in the documentation, thinking that if it was relevant, then it would be repeated on the page they were consulting. In fact, I spend a rather large portion of my time explaining how to read our very poor documentation!

**Comment by wbhart** [comment] 2019-11-22 13:37
Also, I can tell from the emails I keep getting and comments I get at conferences that a great number of users refer to the online documentation as their primary source of information.

I have not done a survey, but I personally have very sincere doubts that a majority of users make use of the REPL help as their first point of contact with the help system.

I do accept that there are some users who do. Perhaps it is also just a cultural thing. I don't know. But neither system should cripple the other.

**Comment by fieker** [comment] 2019-11-22 13:45
On Fri, Nov 22, 2019 at 05:31:03AM -0800, wbhart wrote:
> @fieker I am not disagreeing with you on any of these points. It's not that I don't think there should be docstrings, or that terseness in what is presented in the Julia REPL help is not desirable. It absolutely is!
> 
> I'm simply asking a question: "how are you going to handle documenting
> functions where a one-size-fits-all docstring does not apply". I gave
> examples.
By having a long text scroll over the screen - it cannot be helped.
Forcing people to go a different application here is not going to work.
> 
> At present, we pull in a good proportion of all the docstrings
> currently given, somewhere in the documentation.
> 
> If it would not embarrass actual living people who use our stuff, I
> would post here copies of the emails in which they were clearly
> reading our documentation, but obviously ignored the links to
> elsewhere in the documentation, thinking that if it was relevant, then
> it would be repeated on the page they were consulting. In fact, I
> spend a rather large portion of my time explaining how to read our
> very poor documentation!

That is normal and will never change. The system is large and complex
and various aspects can only be understood in connection to the
underlying cornerstones, hence not at all.
A good documentation helps - but in the end, you're going to spend your
time explaining where, in the documentation, the missing information
is. I don't think there is a way of organizing several thousand pages in
such a way that you can find info - not knowing our keyword.

The key goal is that for most functionality you don't need the
documentation: a function issurjective, applied to a map needs to do
exactly that - or throw an error. A goal is to never have to use
issurjective_in_my_case as no-one will ever fund it (or worse:
my_is_surjective_special)
However, for other functions, documentation is essential: are we solving
Ax=b or xA = b?
Including right or left in the name does not help, while a docstring
will.

**Comment by wbhart** [comment] 2019-11-22 14:02
@fieker I agree with all of this. But I don't believe it solves the problem here.

I would restrict the rationalisation of the documentation to the following:

* the function is documented as a required function for all rings

OR

* the function is provided generically for all rings

AND

* the function does not change meaning depending on the ring, in most cases

But, then we must (as @rfourquet 
 suggests) add a link in the documentation at all the current places where the old docstrings have been removed, to the more general version in the docs, with the name of the function and its original arguments still given in the original location, so that the user has to do minimal clicking to get some useful documentation.

I STRONGLY recommend (based on my interaction with users) that we remove the links in the Nemo documentation to the AbstractAlgebra interface documentation and instead replace them with multiple links to all the relevant functions, a la the links mentioned above. 

Start with just this. If it works out, we can extend it further to other interfaces, e.g. functions defined for all fields, etc.

At the present moment, I don't see how this will actually work, and if it could work, I would make use of such links also in the Oscar documentation. But even for the integers, we currently have such a hodge-podge of signatures that are accepted, that no such links could hope to document the complexity of when you can and cannot use certain types in different parts of the signature, and what return type you are likely to get.

Consider div(::Int, Int) -> Int, div(::BigInt, ::BigInt) -> BigInt, div(::fmpz, ::fmpz) -> fmpz. Seems fine until you consider div(::fmpz, ::Int) -> fmpz, div(::Int, ::fmpz) -> fmpz, and any number of variations on the theme, including accepting Integer, returning an Int instead of an fmpz, etc.

**Comment by wbhart** [comment] 2019-11-22 14:08
And before anyone says, "but I think we should accept Integer everywhere we accept an fmpz", consider that we have Gap.Integer, Singular.Z_n, Polymake.Integer, and the return types are not easy to figure out from the inputs in any case.

And integers are easy to add the extended signatures to (except when they are not). Adding the necessary functionality for some complex number field functionality isn't so easy. You can't just assume that every meaningful input is going to have a corresponding signature implemented.

Moreover, simply doing a coercion from Integer->Int and raising an exception if there is an overflow just misleads the user into thinking they can do their computation with large Integers, only to have their computation inexplicably give an error after running for a month on a large cluster. It *must* be clear to the user before using the function what the effective limits are. That can only be documented on a case-per-case basis, which almost completely destroys any argument about rationalising documentation.

**Comment by fieker** [comment] 2019-11-22 14:26
On Fri, Nov 22, 2019 at 06:08:07AM -0800, wbhart wrote:
> And before anyone says, "but I think we should accept Integer
> everywhere we accept an fmpz", consider that we have Gap.Integer,
> Singular.Z_n, Polymake.Integer, and the return types are not easy to
> figure out from the inputs in any case.
Yep, that's why to normal users, Singular.Z_n and the others should be
unknown and invisible...
> 
> And integers are easy to add the extended signatures to (except when
> they are not). Adding the necessary functionality for some complex
> number field functionality isn't so easy. You can't just assume that
> every meaningful input is going to have a corresponding signature
> implemented.
Yep, you loose in all ways.
> 
> Moreover, simply doing a coercion from Integer->Int and raising an
> exception if there is an overflow just misleads the user into thinking
> they can do their computation with large Integers, only to have their
> computation inexplicably give an error after running for a month on a
> large cluster. It *must* be clear to the user before using the
> function what the effective limits are. That can only be documented on
> a case-per-case basis, which almost completely destroys any argument
> about rationalising documentation.
Even worse: the chances of that lost and the documentation being
actually complete and correct are minimal. Missing cases wil be added
and debugged frequently and, with the exception of Bill doing this, be
documented.

I guess, there are essentially self-explaining functions (+, *), easily
explained ones (div, divexact) and strange ones (order in general)
THe docstring should be readable and conveying the essential information
(adds the input) with the understanding that restrictions could apply
(overflow)
It would be good if a complete reference would exist (for emergency) but
I have yet to see this for anything...

**Comment by fingolfin** [comment] 2021-01-12 00:21
I just stumbled over this issue, and really would like to make progress. I must say I largely agree with most (if not everything) @rfourquet and @fieker wrote. Yes, there are places where we need to do something different -- then we'll do something different? Yes, just docstrings won't be enough, but I think good docstrings are vital; but of course the also need to appear int the manual in a suitable way, but that's assumed anyway.

Of course we shouldn't blindly unify all docstrings; yes, for some functions, we'll want to document multiple methods (just like Julia does it), but for many, this is not needed. I don't think that should stop is.

On a meta level,  I think the problem really is the (to the user) arbitrary split of the documentation into many manuals, corresponding to the various packages (AbstractAlgebra, Nemo, Hecke, Oscar, and more) -- I believe the only realistic way to overcome this is to have a single "Oscar manual" which contains everything. But that's actually independent of this issue discussed here, so even if you disagree with me here, I don't think that should stop us from finally resolving this, at least in the specific case of `divexact.`.

Anyway, the current state is IMHO *bad* because also searching for `divexact` in the manual is semi-broken: it returns four hits for me; none go directly to the information I need, I still need to search for `divexact` (on two of the results; the other two don't document `divexact` at all):
```
Required functionality for inexact rings (section, Ring Interface)
Required functionality for inexact rings (section, Noncommutative ring Interface)
Ring Interface (page)
Matrix Interface (page)
```

So all in all, I think it's bad this discussion got stalled, we need to improve this. There are too many hypothetical concerns that are thrown around, and which we can't settle by mere discussion; we need a prototype of the proposed change, then we can discuss that, and see if it made anything worse, and then decide how to continue.

@rfourquet could you please make a PR for this repo which unifies the `divexact` docstrings in this repo into a single one, as discussed? Then we can look at the concrete result and then look into proceeding with further similar functions (and also doing the same in `Nemo` and perhaps elsewhere). An immediate candidate are the arithmetic functions; e.g. `?*` also lists a gazillion useless results.

**Comment by wbhart** [comment] 2021-05-18 22:34
It looks like the divexact issue was sorted out. The issue is otherwise too vague to be actionable. We should open tickets for specific functions with too many docstrings (if any still remain).

**Closed by wbhart** 2021-05-18 22:34 UTC
Labels: doc
