### ISSUE TITLE
New printing lowercases too much

### ISSUE THREAD

**Issue by fingolfin** [Nemocas/AbstractAlgebra.jl#1449] opened 2023-09-27 11:02 UTC
(I could have sworn I submitted this issue already yesterday but not can't find it anymore. Sorry if I posted it twice now).

In the new printing code we try to avoid grammatically wrong captialization in the middle of text, and use constructs like `print(io, Lowercase(), base_ring(X))` for that.

So that instead of `BLA over Polynomial ring` we print `BLA over polynomial ring`.

But if rings with a name are involved, this is a bad idea. E.g. if the base ring has the name `F` then now we print `BLA over f` instead of `BLA over F` which is annoying.

Perhaps `@show_name` just should insert a `LowercaseOff()` before printing the name. Though I wonder if this can't cause more errors. Consider this hypothetical example:
```
print(io, "group ring with coefficients in ", Lowercase(), base_ring(X), " over ", base_group(X))
```
If the first `base_ring(X)` is printed with a name, it will turn off Lowercase mode, but then it is also off for the group later on... So perhaps we also need to remember the state of the lowercase flag and possibly turn it back on?

**Comment by thofma** [comment] 2023-09-27 15:33
Would
```
print(io, "group ring with coefficients in ", Lowercase(), base_ring(X), " over ", Lowercase(), base_group(X))
```
solve the problem?

**Comment by fingolfin** [comment] 2023-09-28 08:57
Indeed, I misremember the definition of `Lowercase()` -- it only affects one character. So my hypothetical example was wrong anyway.

**Comment by fingolfin** [comment] 2023-09-28 08:57
So the fix is quite simple

**Comment by fingolfin** [comment] 2023-09-28 09:42
I actually have trouble finding a test case outside of Jupyter *sigh*

**Comment by fingolfin** [comment] 2023-09-28 09:45
I can replicate it in Hecke or Oscar, though:
```
julia> F = cyclotomic_field(5)[1];
Number field with defining polynomial _$^4 + _$^3 + _$^2 + _$ + 1
  over rational field

julia> vector_space(F, 6)
Vector space of dimension 6 over f
```

**Comment by fingolfin** [comment] 2023-09-28 09:46
Ah and that's because Hecke frequently activates `IOContext(io, :compact => true)` in places were we now would maybe suggest to use `IOContext(io, :supercompact => true)` ... only the former activates printing of the "name" of an object, but not the latter.

**Comment by thofma** [comment] 2023-09-28 13:21
OK. I will close this for now, since we convinced ourselves that things should compose well by design.

**Closed by thofma** 2023-09-28 13:21 UTC
