### ISSUE TITLE
Allow K[x, y]/|(f) using divrem(a, [b]) to get unique representatives mod [b] ??

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#737] opened 2021-02-01 15:54 UTC
Seems to be an mpoly problem as it works well with univariates?

```julia
julia> using AbstractAlgebra

julia> Qxy,(x,y) = PolynomialRing(QQ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y])

julia> R = ResidueRing(Qxy, x^3+y^2+1)
Residue ring of Multivariate Polynomial Ring in x, y over Rationals modulo x^3 + y^2 + 1

julia> R(x)
ERROR: MethodError: no method matching mod(::AbstractAlgebra.Generic.MPoly{Rational{BigInt}}, ::AbstractAlgebra.Generic.MPoly{Rational{BigInt}})


julia> Qx,x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rationals, x)

julia> R = ResidueRing(Qx, x^3+2)
Residue ring of Univariate Polynomial Ring in x over Rationals modulo x^3 + 2

julia> R(x)^6
4
```

**Comment by thofma** [comment] 2021-02-01 16:03
What should it do? The ring is not Euclidean. At the moment the `ResidueRing` thing accepts everything, but it does not always produce something useful.

**Comment by tthsqe12** [comment] 2021-02-01 16:08
> What should it do?

I dunno :). All I want to do is work in QQ(x, sqrt(x^3+1)). That should be possible with this construction, right?

**Comment by thofma** [comment] 2021-02-01 16:10
You mean Q[x,y]/(x^3 + y^2 + 1)? No, this is not possible with AA as far as I understand. You can use Oscar for this though!

**Comment by tthsqe12** [comment] 2021-02-01 16:13
Well, to make `QQ(x, sqrt(-x^3-1))` (the field), I would do `FractionField(R)` where `R` is the thing that doesn't work. So the first step doesn't work.

**Comment by thofma** [comment] 2021-02-01 16:15
How about constructing it as `QQ(x)[y]/(y^2 + x^3 + 1)`?

**Comment by tthsqe12** [comment] 2021-02-01 16:16
I didn't want to do it that way :). It should work this way too.

**Comment by tthsqe12** [comment] 2021-02-01 16:34
Ok - so I realize that in order to construct `FractionField(R)`, it would be a good idea if `R` were an integral domain, and even better if `R` were a gcd domain. However, is it really the intention to have `ResidueRing(Qxy, x^3+y^2+1)` be completely useless?

**Comment by wbhart** [comment] 2021-02-01 17:06
What does ResidueRing(Qxy, x^3+y^2+1) mean? Do you want the quotient ring of Qxy by the ideal generated by x^3+y^2+1?

That's an extraordinarily difficult thing to implement generically. Even if you have the special case of polynomial rings, you might need a Groebner basis. So yeah, this isn't going to be in AA any time soon.

**Comment by tthsqe12** [comment] 2021-02-01 17:15
Is it really the hard to modulo by a principal ideal? All you need is a mod(a,b) function that returns 0 when b divides a..

**Comment by wbhart** [comment] 2021-02-01 17:18
It's not a Euclidean domain. How are you even going to specify representatives? You will literally end up reinventing Groebner bases.

**Comment by tthsqe12** [comment] 2021-02-01 17:27
How are you even going to specify representatives?
The elements of R/(a) are f + aR where f is in R. You can just use the elements of R.
If the mod(f,a) function makes f smaller, then you can use the output of that if you want too.
Then, for equality testing and zero testing, you need divisibility by a, which I assume you have.

**Comment by wbhart** [comment] 2021-02-01 17:30
This is only going to work for PIDs. Do you have a general way to test if the input ring is a PID?

**Comment by wbhart** [comment] 2021-02-01 17:32
SageMath does have something like this, by the way. But they express everything in terms of ideals, not elements. That would be the correct mathematical way of handling this. But then the user has to know whether their ring is suitable.

I wouldn't say we don't intend to implement something like this eventually. We just haven't yet.

**Comment by wbhart** [comment] 2021-02-01 17:33
In any event, how are you going to handle output? Are you going to use representatives in R for that too? I don't see that as being particularly helpful to the user.

**Comment by tthsqe12** [comment] 2021-02-01 17:54
I think you might under the false impression that I am suggesting the representative in R be unique.

Given that coercion `x` into `ResidueRing(Qxy, x^3+y^2+1)` does not work, I would say that currently `ResidueRing` is not very useful. So I looked through the required functions for every ring, and there are 2 problems:
- hash: oh well
- divexact: here we would need some kind of xgcd to be working over R.

However, there is a bigger issue here. `mod` is not in the required interface for rings, but yet the existing construction of `ResidueRing` relies on it. Hence the existing implementation is just as broken as what I am suggesting :)

**Comment by wbhart** [comment] 2021-02-01 18:24
No I am not under the impression that the representatives in R are unique.

How are you going to get an xgcd in a non-Euclidean domain? You can extend to a gcd domain so long as there is an effective algorithm, but this is a major problem in general when you don't have a Euclidean domain.

Hash is actually a serious problem. Some functionality such as sets will end up with duplicate entries without a working hash. You can't just brush stuff like that off. The user cannot be expected to know they are getting wrong answers because they don't have a deep knowledge of all the implementation decisions. You therefore can't offer functionality that doesn't actually work in general.

And mod is not meant to be in the required interface for rings. How on earth would you implement mod for a ring that wasn't Euclidean? Obviously it can't be done (even in theory).

Instead mod is in the interface for Euclidean domains because it relies on Euclidean division.

Your ring isn't Euclidean. It's not just that I don't know a Euclidean structure for it. It actually isn't Euclidean.

You can't just expect the system to Just Work TM for any arbitrary ring you pick. It has to actually work for a class of rings, and all the infrastructure for that has to be there. And then everything has to be consistent. It's far worse to mislead the user with wrong answers because the system claims to do things it actually cannot.

**Comment by tthsqe12** [comment] 2021-02-01 18:24
So is it safe to say that `ResidueRing(R, a)` currently only works when `R` is a euclidean domain, and all of the euclidean functions have been provided?

**Comment by wbhart** [comment] 2021-02-01 18:26
Yes, that should be a safe assumption at present, especially as that is what the documentation says in the first paragraph:

https://nemocas.github.io/AbstractAlgebra.jl/latest/residue_rings/

**Comment by wbhart** [comment] 2021-02-01 18:28
As I said, it may be possible to extend the implementation of residue rings to PIDs. But don't quote me on it. I haven't thought it through carefully and it certainly hasn't been done at present.

Of course your ring isn't a PID either.

**Comment by tthsqe12** [comment] 2021-02-01 18:30
Ok, I got it. The system is not meant to "Just work". But then how would you implement divides in R/(a) for non-PID?

As for hashing, it is depressing that we have to define a hash on elements of R such that: if x == y in R, then hash(x) and hash(y) should be the same.

**Comment by wbhart** [comment] 2021-02-01 18:36
The system can't be made to Just Work TM. You should read Groups, Rings, Modules by Auslander and Buchsbaum. Although it contains hundreds of errors, it gives some idea of the complexity of this stuff generally. There are open mathematical problems...

I'm not sure what you are asking regarding divides in R/(a) for non-PID. You mean with R non-PID? How should I know. Why do you need to know that? We don't even support such a construction. A Euclidean domain is a PID.

As for hashing, that is a requirement of Julia. One can always define the hash to return 0 I suppose. Then an actual equality test will be done before putting things in the same set. I'm sure this is one of many design decisions that would need to be considered to do what you want to do.

And then at the end of the day, what have you achieved? You've just duplicated work that is going on in Oscar.jl right now.

**Comment by wbhart** [comment] 2021-02-01 18:42
The other thing that I think you are missing is that if you implement more general residue rings (they are called quotient rings), then all the stuff that is built on top of residue rings will also break. How should polynomials, series, matrices, etc., over quotient rings be handled?

The stuff doesn't even work for Z/nZ right now.

**Comment by tthsqe12** [comment] 2021-02-01 18:58
Yeah I mean divisibility testing in R/a for R not a PID. It looks like singular does this, and of course it is way too much work for AA to do it.

**Comment by wbhart** [comment] 2021-02-01 19:02
I am not convinced Singular does this for arbitrary rings. It is usually limited (with some exceptions) to multivariate polynomial rings.

**Comment by thofma** [comment] 2021-02-01 20:30
There is actual something we could do. We could use `divrem(b, [a])` to get unique representatives modulo `a`. This will work since `{a}` is a Gröbner basis and so the flint divrem will provice unique representatives.

**Comment by thofma** [comment] 2021-02-01 20:33
(What we get won't work too well with `FractionField`. As you observed, `FractionField` basically wants to have a base ring which is a GCD domain).

**Comment by wbhart** [comment] 2021-02-01 20:42
It's a Groebner basis if you have a polynomial ring. I'm not sure it makes sense generically.

But if we are going to restrict to polynomial rings only, then Z[x, y], Q[x, y] etc are gcd domains.

**Comment by thofma** [comment] 2021-02-01 20:44
I was talking about the original problem of Dan. He wants to construct `R =Q[x,y]/(f)`. This will work using the `divrem` provided by flint. Then he wants to form the `FractionField`, which won't work too well for `R` (one can construct it, but basic functionality won't work).

**Comment by wbhart** [comment] 2021-02-01 20:49
Yeah in my opinion it is a bad idea to extend the range of residue rings in AA without considering all the constructions possible over them. And if we are going to do that much work, we may as well do it properly and work out what the biggest extension of the system we can get away with in one go.

So yeah, we'd have to work on a pile of other modules as well, FractionField being one of them.

And of course I really don't want to make everything more generic at the expense of massive performance regressions to what is already there. I think the job is really quite involved. This is one example of why I think the incremental approach to CAS's does not converge.

**Comment by fieker** [comment] 2021-02-02 08:20
There are 2 completely different issues here - that should not be mixed:
 - in AA (here), generic ResidueRings are implemented for euclidean rings only - but this cannot be inferred by type. Follow up from here, the generic FractionField is also requiring the euc interface
 - in Oscar (or AA), of course, ResidueRing, quo, ... need to work for Q[x,y]. In fact partly they already do

**Comment by fieker** [comment] 2021-02-02 08:34
in (current) (dev) (future) Oscar
julia> quo(Qxy, x^3+y^2-2)
(Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^3 + y^2 - 2, Map from
Multivariate Polynomial Ring in x, y over Rational Field to Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^3 + y^2 - 2 defined by a julia-function with inverse
)

julia> quo(Qxy, x^3+y^2-2, x^3)
(Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^3 + y^2 - 2, x^3, Map from
Multivariate Polynomial Ring in x, y over Rational Field to Quotient of Multivariate Polynomial Ring in x, y over Rational Field by ideal generated by: x^3 + y^2 - 2, x^3 defined by a julia-function with inverse
)

**Comment by wbhart** [comment] 2021-05-18 22:25
Can I close this issue @thofma @tthsqe12 ? I don't see anything actionable here. If you see something that I don't, could you possibly write up a proposal on a separate ticket.

**Comment by tthsqe12** [comment] 2021-05-19 06:45
Yup, nothing actionable here from my point of view. The fraction field + polynomial ring is going to need a separate construction.

**Closed** 2021-05-19 10:11 UTC
