### ISSUE TITLE
MatrixAlgebras, MatrixSpaces and inv

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#287] opened 2019-03-29 10:17 UTC
```julia
julia> using AbstractAlgebra

julia> M = MatrixSpace(AbstractAlgebra.ZZ, 2,2)
Matrix Space of 2 rows and 2 columns over Integers

julia> m = M(1); m[1,2] = 1; m
[1 1]
[0 1]

julia> inv(m)
([-1 -1]
[0 -1], 1)
```
we return pair here (its fine, since matrix spaces don't necessarily have multiplication), but what kind of inverse is this?
```julia
julia> m*inv(m)[1]
[-1 -2]
[0 -1]

julia> inv(m)[1]*m
[-1 -2]
[0 -1]
```

Lets try `MatrixAlgebra`s:
```julia
julia> M = MatrixAlgebra(AbstractAlgebra.ZZ, 2)
Matrix Algebra of degree 2 over Integers

julia> m = M(1); m[1,2] = 1; m
[1 1]
[0 1]

julia> inv(m)
([-1 -1]
[0 -1], 1)
```
Besides the inverse being again wrong, why do we return a pair? (I'd expect either the inverse or `Error`, as in the case of `ResidueRings`). ;

Lets try `Nemo.ZZ` ring:
```julia
julia> M = MatrixAlgebra(Nemo.ZZ, 2);

julia> m = M(1); m[1,2] = 1; m
[1 1]
[0 1]

julia> inv(m)
([1 -1]
[0 1], 1)

```
here the answer is correct, but again why pair is returned?
Finally:
```julia
julia> M = MatrixSpace(Nemo.ZZ, 2, 2);

julia> m = M(1); m[1,2] = 1; m
[1 1]
[0 1]

julia> inv(m)
[1 -1]
[0 1]

```

In general I'd be happiest if `inv(::MatAlgElem)` (or `inv(::NCRingElem)`) return an honest inverse or `throw` if element is not invertible; It makes more sense to return pair `(m^{-1}, leading_coeff)` for `MatElems`

**Comment by thofma** [comment] 2019-03-29 10:34
Agree with everything you say. We should just throw if it is not invertible. There is `pseudo_inv` for `fmpz_mat`, which returns the pair.

**Comment by wbhart** [comment] 2019-03-29 10:35
Yeah I don't know why it is doing that. Definitely a bug.

**Comment by kalmarek** [comment] 2019-03-29 10:40
is it something fixable quickly? then I can start hacking on this;
If it's more complicates I'd leave it for the more experienced You ;-)
(I actually don't know the algorithm for inverting matrices over a ring. Is it a standard Gaussian with pivoting? what kind of pivoting strategy is done then?)

anyway: if both `Nemo` and `AbstractAlgebra` provide similar functionality maybe it's good idea to test them against each other?

**Comment by wbhart** [comment] 2019-03-29 10:50
It's trivial to fix that specific issue, but we'll need to look for every occurrence of inv and make sure it calls pseudo_inv instead (which this function will have to be named to in line with Nemo) whenever we aren't over a field.

As to why it is returning completely the wrong answer, I do not know. But presumably it's some stupid bug, which just needs tracking down.

**Comment by wbhart** [comment] 2019-03-29 10:54
I think one of us will have to track down the reason for it giving the wrong answer. It might be due to the new delayed reduction code I added, or something like that.

**Comment by wbhart** [comment] 2019-03-29 12:03
The algorithm is to do a fraction free LU decomposition (as a precomputation), then solve AX = I using the precomputation.

Regarding test code, yes, Nemo should have much better test code. No one has yet found time to fix it. Also, the test code for matrices in AbstractAlgebra is still a bit lacking in places, compared to the rest of AbstractAlgebra.

**Comment by wbhart** [comment] 2019-03-29 12:18
Claus found the problem with the incorrect answer at least. When the matrix was created, it was putting the same (BigInt) object for each entry on the diagonal of the matrix, instead of putting copies. I've made a pull request to fix that.

**Comment by wbhart** [comment] 2019-03-29 12:39
Actually, the problem is more complex than that. Deepcopy of Julia matrices of BigInts preserves identity between element that are the same. Therefore, doing a deepcopy of a matrix is not enough when you want to apply a mutating function to it.

**Comment by wbhart** [comment] 2019-03-29 17:32
The issue with the incorrect results is now fixed in master. I haven't attempted to fix the return of a pair though.

**Comment by kalmarek** [comment] 2019-04-03 08:57
is there a reason why we don't use `@testset`s etc?

**Comment by thofma** [comment] 2019-04-03 09:03
Only historical reasons :)

**Comment by thofma** [comment] 2019-04-03 09:04
And (in principle) you can include the test files and run the single test functions in the REPL.

**Closed** 2019-04-06 13:33 UTC
